package com.coding.miaosha.dao;

import com.coding.miaosha.dataobject.ItemStockDO;

public interface ItemStockDOMapper {
  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table item_stock
   *
   * @mbg.generated Wed Feb 12 14:12:34 JST 2020
   */
  int deleteByPrimaryKey(Integer id);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table item_stock
   *
   * @mbg.generated Wed Feb 12 14:12:34 JST 2020
   */
  int insert(ItemStockDO record);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table item_stock
   *
   * @mbg.generated Wed Feb 12 14:12:34 JST 2020
   */
  int insertSelective(ItemStockDO record);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table item_stock
   *
   * @mbg.generated Wed Feb 12 14:12:34 JST 2020
   */
  ItemStockDO selectByPrimaryKey(Integer id);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table item_stock
   *
   * @mbg.generated Wed Feb 12 14:12:34 JST 2020
   */
  int updateByPrimaryKeySelective(ItemStockDO record);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table item_stock
   *
   * @mbg.generated Wed Feb 12 14:12:34 JST 2020
   */
  int updateByPrimaryKey(ItemStockDO record);
}