package com.coding.miaosha.dao;

import com.coding.miaosha.dataobject.ItemDO;

public interface ItemDOMapper {
  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table item
   *
   * @mbg.generated Wed Feb 12 14:12:34 JST 2020
   */
  int deleteByPrimaryKey(Integer id);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table item
   *
   * @mbg.generated Wed Feb 12 14:12:34 JST 2020
   */
  int insert(ItemDO record);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table item
   *
   * @mbg.generated Wed Feb 12 14:12:34 JST 2020
   */
  int insertSelective(ItemDO record);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table item
   *
   * @mbg.generated Wed Feb 12 14:12:34 JST 2020
   */
  ItemDO selectByPrimaryKey(Integer id);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table item
   *
   * @mbg.generated Wed Feb 12 14:12:34 JST 2020
   */
  int updateByPrimaryKeySelective(ItemDO record);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table item
   *
   * @mbg.generated Wed Feb 12 14:12:34 JST 2020
   */
  int updateByPrimaryKey(ItemDO record);
}