package com.coding.miaosha.dao;

import com.coding.miaosha.dataobject.UserDO;

public interface UserDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated Fri Jan 31 10:45:49 JST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated Fri Jan 31 10:45:49 JST 2020
     */
    int insert(UserDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated Fri Jan 31 10:45:49 JST 2020
     */
    int insertSelective(UserDO record);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table user_info
   *
   * @mbg.generated Fri Jan 31 10:45:49 JST 2020
   */
  UserDO selectByPrimaryKey(Integer id);

  UserDO selectByTelephone(String telephone);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table user_info
   *
   * @mbg.generated Fri Jan 31 10:45:49 JST 2020
   */
  int updateByPrimaryKeySelective(UserDO record);

  /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated Fri Jan 31 10:45:49 JST 2020
     */
    int updateByPrimaryKey(UserDO record);
}